# Generated by Django 6.0.7 on 2026-07-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_label', models.CharField(max_length=200)),
                ('folder_name', models.CharField(max_length=255)),
                ('folder_path', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('number_of_files', models.IntegerField()),
                ('size', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
